image: node:latest

cache:
  paths:
    - node_modules/

before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass

deploy_production:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - npm install
    - node_modules/.bin/gatsby build --prefix-paths
    - sshpass -V
    - export SSHPASS=$USER_PASS 
    - sshpass -e scp -o stricthostkeychecking=no -r /builds/kubabirnbach/chyba-ty-tattoo/public root@46.101.215.125:/var/www/html/chyba-ty-tattoo
