image: node:latest

cache:
  paths:
    - node_modules/

before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass

deploy_production:
  stage: deploy
  environment: 
    name: production
  only:
    - master
  script:
    - npm install
<<<<<<< HEAD
<<<<<<< HEAD
<<<<<<< HEAD
    - echo "GOOGLE_MAP_API_KEY=$GOOGLE_MAP_API_KEY" > "$(pwd)/.env.production"
    - cat .env.production
    - ls -al
=======
    - export GOOGLE_MAP_API_KEY=$GOOGLE_MAP_API_KEY
>>>>>>> 84e4d5b... env config changed 16
=======
    - export GATSBY_GOOGLE_MAP_API_KEY=$GATSBY_GOOGLE_MAP_API_KEY
<<<<<<< HEAD
>>>>>>> d1c0d1e... env config changed 19
=======
=======
>>>>>>> 08792d9... env config changed 22
    - echo GATSBY_GOOGLE_MAP_API_KEY=$GATSBY_GOOGLE_MAP_API_KEY > .env.production
    - ls -al
>>>>>>> 781e06b... env config changed 21
    - node_modules/.bin/gatsby build
    - sshpass -V
    - export SSHPASS=$USER_PASS 
    - sshpass -e scp -o stricthostkeychecking=no -r /builds/kubabirnbach/chyba-ty-tattoo/public root@46.101.215.125:/var/www/html/chyba-ty-tattoo
