image: node:latest

cache:
  paths:
    - node_modules/
    - .cache/
    - public/

before_script:
    - apt-get update -qq && apt-get install -y -qq sshpass

deploy_production:
  stage: deploy
  environment: 
    name: production
  only:
    - master
  script:
    - npm install
    - echo "GOOGLE_MAP_API_KEY=$GOOGLE_MAP_API_KEY"
    - echo "GOOGLE_MAP_API_KEY=$GOOGLE_MAP_API_KEY" > "$(pwd)/.env.production"
    - cat .env.production
    - ls -ll
    - node_modules/.bin/gatsby build --prefix-paths
    - sshpass -V
    - export SSHPASS=$USER_PASS 
    - sshpass -e scp -o stricthostkeychecking=no -r /builds/kubabirnbach/chyba-ty-tattoo/public root@46.101.215.125:/var/www/html/chyba-ty-tattoo
  artifacts:
    paths:
      - public
